#ifndef __TJC_SCREEN_H_
#define __TJC_SCREEN_H_

#include "main.h"
#include <stdbool.h>
#include <stdint.h>

#define TJC_TIME_WAVEFORM_ID        12U
#define TJC_TIME_DISPLAY_POINTS     257U
#define TJC_TIME_CYCLES_ONE         1U
#define TJC_TIME_CYCLES_THREE       3U
#define TJC_TOUCH_CMD_TIME_START    0x01U
#define TJC_TOUCH_CMD_TIME_STOP     0x02U
#define TJC_TOUCH_CMD_TIME_TOGGLE   0x03U
#define TJC_TOUCH_CMD_FREQ_START    0x11U
#define TJC_TOUCH_CMD_FREQ_STOP     0x12U
#define TJC_FREQ_PLOT_WIDTH         434U
#define TJC_MAX_FREQUENCY_COMPONENTS 3U

typedef struct
{
    float time_ms;
    float voltage_mv;
} TJC_TimePoint;

typedef struct
{
    float frequency_khz;
    float amplitude_mv;
} TJC_FrequencyPoint;

extern uint8_t g_usart1_rx_byte;

/**
 * Start the USART1 byte interrupt used by both touch frames and addt replies.
 */
HAL_StatusTypeDef TJC_Init(void);

/**
 * Feed one received USART1 byte to the TJC protocol state machine.
 * Call this from HAL_UART_RxCpltCallback().
 */
void TJC_UART_RxCpltCallback(uint8_t rx_data);

/**
 * Read one touch command generated by the screen.
 * Returns true once for every valid AA 01 command 55 frame.
 */
bool TJC_GetTouchCommand(uint8_t *command);

/**
 * Send one ordinary TJC command followed by FF FF FF.
 */
void TJC_SendCmd(const char *fmt, ...);

/**
 * Send raw 0..255 waveform samples with the TJC addt handshake.
 * The target page containing waveform_id must already be active.
 */
HAL_StatusTypeDef TJC_StreamWaveform(uint8_t waveform_id,
                                     uint8_t channel,
                                     const uint8_t *samples,
                                     uint16_t sample_count,
                                     uint32_t timeout_ms);

/**
 * Display a time-voltage array on page 1.
 *
 * The input time values must be monotonically increasing and must cover at
 * least 3.2 complete periods. The driver prepares a one-period buffer and a
 * slightly-more-than-three-period buffer, then draws the selected mode with
 * line commands over the time-domain picture component p0.
 * Voltage zero maps to the middle horizontal axis.
 * voltage_full_scale_mv is the positive/negative half-range; pass 0 to
 * auto-scale from the largest absolute input voltage.
 */
HAL_StatusTypeDef TJC_UpdateTimeDomain(const TJC_TimePoint *points,
                                       uint16_t point_count,
                                       float voltage_full_scale_mv,
                                       float upp_mv,
                                       float rms_mv,
                                       float fundamental_hz);

/**
 * Select or toggle the time-domain window between 1 and 3 complete periods.
 * Once time-domain data has been loaded, changing the mode redraws the cached
 * waveform immediately without requesting the array from the FPGA again.
 */
HAL_StatusTypeDef TJC_SetTimeDisplayCycles(uint8_t cycle_count);
HAL_StatusTypeDef TJC_ToggleTimeDisplayCycles(void);
uint8_t TJC_GetTimeDisplayCycles(void);

/**
 * Display up to three discrete vertical spectrum lines on page 2.
 *
 * Put the fundamental first, followed by up to two harmonics. Frequencies are
 * mapped proportionally over 0..display_max_frequency_khz, so harmonic
 * multiples remain visually clear. Amplitudes are mapped over
 * 0..amplitude_full_scale_mv. Pass 0 for either range to auto-scale with
 * a small display margin.
 */
HAL_StatusTypeDef TJC_UpdateFrequencyDomain(const TJC_FrequencyPoint *components,
                                            uint8_t component_count,
                                            float display_max_frequency_khz,
                                            float amplitude_full_scale_mv);

void TJC_UpdateTimeText(float upp_mv, float rms_mv, float fundamental_hz);

void TJC_UpdateSpectrumText(uint8_t component_count,
                            float f1_khz, float a1_mv,
                            float f2_khz, float a2_mv,
                            float f3_khz, float a3_mv);

#endif /* __TJC_SCREEN_H_ */
