% VCD File Parser for Verilog Simulation Results
% This script parses VCD files generated by Vivado simulation

function [time_us, cha_data, chb_data] = parse_vcd(vcd_file)
    % Open VCD file
    fid = fopen(vcd_file, 'r');
    if fid == -1
        error('Cannot open VCD file: %s', vcd_file);
    end
    
    fprintf('Parsing VCD file: %s\n', vcd_file);
    
    % Initialize variables
    time_us = [];
    cha_data = [];
    chb_data = [];
    timestamp = 0;
    
    % Variable mappings (will be populated from $var declarations)
    var_map = containers.Map();
    cha_var = '';
    chb_var = '';
    clk_var = '';
    
    % Read file line by line
    while ~feof(fid)
        line = fgetl(fid);
        
        if ischar(line)
            % Handle timestamp
            if line(1) == '#'
                timestamp = str2double(line(2:end));
            % Handle variable declarations
            elseif contains(line, '$var')
                parts = strsplit(line);
                if length(parts) >= 4
                    var_name = parts{4};
                    var_code = parts{4};
                    if contains(line, 'cha_data')
                        cha_var = var_code;
                    elseif contains(line, 'chb_data')
                        chb_var = var_code;
                    end
                end
            % Handle value changes
            elseif length(line) > 1 && line(1) == 'b'
                parts = strsplit(line);
                if length(parts) >= 2
                    val_str = parts{1}(2:end);  % Remove 'b' prefix
                    var_code = parts{2};
                    value = bin2dec(val_str);
                    
                    if strcmp(var_code, cha_var)
                        time_us(end+1) = timestamp / 1e6;  % Convert to us
                        cha_data(end+1) = value;
                    elseif strcmp(var_code, chb_var)
                        chb_data(end+1) = value;
                    end
                end
            end
        end
    end
    
    fclose(fid);
    
    fprintf('Parsed %d samples\n', length(time_us));
end
