#!/usr/bin/env python3
"""
gen_luts_2026_G.py
-------------------
根据 G 题频谱分析设计参数,预生成 3 张查找表的初始化 .mem / .coe 文件:

1. HannTable.mem   : 10240 项 Hann 窗系数, 12-bit 无符号 Q0.12 (0..4095)
2. CosTable.mem    : 2560 项 cos(2π k / 10240), 16-bit 有符号 Q1.15 (-32768..32767)
3. SinTable.mem    : 2560 项 sin(2π k / 10240), 16-bit 有符号 Q1.15

输出到  C:\\Users\\24307\\Desktop\\FPGA_windows\\Vivado\\verliog\\A0_1\\A0_1.srcs\\sources_1\\imports\\A0_1\\
即 design 的 source 目录 (便于 Vivado 通过 add_files 即时识别).

另外额外输出当前目录 *.decimal.txt, 便于 verilator 仿真直接用 $readmemh (十六进制) 加载.

设计参数 (与 2026_G.md 一致):
    fs = 5 MHz
    N  = 10240 sample (2.048 ms / 帧)
    df = 5 MHz / 10240 = 488.28125 Hz
    Bins = 2560 (覆盖 0 ~ 1250 kHz)
"""

import math
import os
import sys
import argparse

# ----------------------------------------------------------------------------
# 固定参数
# ----------------------------------------------------------------------------
N_FRAME     = 10240     # 每帧 sample 数
N_BIN       = 2560      # 频点 bin 数 (覆盖 0 ~ 1250 kHz)
FS_HZ       = 5.0e6     # 采样率

# 输出目录 (Vivado 端的 source_1 dir)
DEFAULT_OUT = r"C:\Users\24307\Desktop\FPGA_windows\Vivado\verliog\A0_1\A0_1.srcs\sources_1\imports\A0_1"

# ----------------------------------------------------------------------------
# 工具: 数 -> 16-bit signed hex (Q1.15)
# ----------------------------------------------------------------------------
def q115(x: float) -> int:
    """把 [-1, +1] 的有符号小数映射为 16-bit Q1.15 整数."""
    val = int(round(x * 32767.0))
    val = max(-32768, min(32767, val))
    return val

def s15_hex(v: int) -> str:
    """16-bit 有符号 -> 16-bit 十六进制 (用于 $readmemh)."""
    if v < 0:
        v = (v + 65536) & 0xFFFF
    return f"{v:04X}"

def u12_hex(v: int) -> str:
    return f"{v:03X}"  # 12-bit, 0..4095

# ----------------------------------------------------------------------------
# 生成 Hann 窗
#   w[n] = 0.5 * (1 - cos(2π n / (N-1))), n = 0..N-1
#   Q0.12 定点 (0..4095)
# ----------------------------------------------------------------------------
def gen_hann() -> list:
    table = []
    for n in range(N_FRAME):
        # 使用 N-1 = 10239 作为分母, 起点/终点严格为 0
        if N_FRAME == 1:
            w = 1.0
        else:
            w = 0.5 * (1.0 - math.cos(2.0 * math.pi * n / (N_FRAME - 1)))
        v = int(round(w * 4095.0))
        v = max(0, min(4095, v))
        table.append(v)
    return table

# ----------------------------------------------------------------------------
# Cos / Sin 表
# ----------------------------------------------------------------------------
def gen_cos_sin() -> tuple:
    cos_t, sin_t = [], []
    for k in range(N_BIN):
        ang = 2.0 * math.pi * k / N_FRAME
        cos_t.append(q115(math.cos(ang)))
        sin_t.append(q115(math.sin(ang)))
    return cos_t, sin_t

# ----------------------------------------------------------------------------
# 写出 $readmemh 加载格式 (一行一个十六进制字)
# ----------------------------------------------------------------------------
def write_mem_hex(path: str, values: list, fmt=str) -> None:
    """每行一个十六进制字, Vivado $readmemh 默认行为.
       末尾补一个 dummy 0 防止 `case` 越界时推断 latch."""
    with open(path, "w", encoding="utf-8") as fp:
        for v in values:
            fp.write(fmt(v) + "\n")
        fp.write("// end-of-table\n")

# ----------------------------------------------------------------------------
# 写出 verilog `case` 格式 (2560 行 case 比 readmemh 推断 BRAM 更稳;
#   在 5 MHz / 10240 项 Hann 上, 综合器可能推断 BRAM 也可能推断 LUTROM,
#   2560 项 LUTROM = 2560 x 16-bit = 5120 LUT-FIFO 等效, 仍绰绰有余).
# ----------------------------------------------------------------------------
def write_case_cos_sin(path_cos: str, cos_t: list, path_sin: str, sin_t: list) -> None:
    def case_str(name: str, t: list) -> str:
        lines = []
        lines.append(f"// Auto-generated by gen_luts_2026_G.py — DO NOT EDIT")
        lines.append(f"// Source-data: {N_BIN} entries of 16-bit signed Q1.15 hex")
        lines.append(f"module {name}(")
        lines.append(f"  input  wire [11:0] io_idx,")
        lines.append(f"  output reg  [15:0] io_val")
        lines.append(f");")
        lines.append(f"  always @* begin")
        lines.append(f"    case (io_idx)")
        for k in range(N_BIN):
            lines.append(f"      12'd{k:>4}: io_val = 16'h{s15_hex(t[k])};")
        lines.append(f"      default: io_val = 16'h0000;")
        lines.append(f"    endcase")
        lines.append(f"  end")
        lines.append(f"endmodule")
        return "\n".join(lines) + "\n"

    with open(path_cos, "w", encoding="utf-8") as fp:
        fp.write(case_str("CosTable", cos_t))
    with open(path_sin, "w", encoding="utf-8") as fp:
        fp.write(case_str("SinTable", sin_t))

def write_case_hann(path: str, hann: list) -> None:
    """HannTable 10240 项 - 用 $readmemh 从 .mem 文件加载, 推断为 BRAM."""
    lines = []
    lines.append("// Auto-generated by gen_luts_2026_G.py — DO NOT EDIT")
    lines.append(f"// Source-data: {N_FRAME} entries of 12-bit unsigned Q0.12 hex")
    lines.append("// Loaded via $readmemh at simulation/synthesis time.")
    lines.append("module HannTable(")
    lines.append("  input  wire         io_clk,")
    lines.append("  input  wire [13:0]  io_idx,")
    lines.append("  output reg  [11:0]  io_val")
    lines.append(");")
    lines.append("  reg [11:0] mem [0:10239];")
    lines.append("  initial begin")
    lines.append("    $readmemh(\"HannTable.mem\", mem);")
    lines.append("  end")
    lines.append("  always @(posedge io_clk) begin")
    lines.append("    io_val <= mem[io_idx];")
    lines.append("  end")
    lines.append("endmodule")
    with open(path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines) + "\n")
    # 同时写出 .mem
    mem_path = os.path.join(os.path.dirname(path), "HannTable.mem")
    with open(mem_path, "w", encoding="utf-8") as fp:
        for v in hann:
            fp.write(f"{u12_hex(v)}\n")

# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", default=DEFAULT_OUT,
                   help="输出目录 (默认为 Vivado A0_1.srcs source_1 路径)")
    args = p.parse_args()

    out_dir = args.out
    os.makedirs(out_dir, exist_ok=True)
    print(f"[gen_luts_2026_G] output dir: {out_dir}")

    hann = gen_hann()
    cos_t, sin_t = gen_cos_sin()

    write_case_hann( os.path.join(out_dir, "HannTable.v"), hann)
    write_case_cos_sin( os.path.join(out_dir, "CosTable.v"), cos_t,
                        os.path.join(out_dir, "SinTable.v"), sin_t)

    print(f"[OK] HannTable.v + HannTable.mem ({N_FRAME} x 12-bit)")
    print(f"[OK] CosTable.v + SinTable.v ({N_BIN} x 16-bit)")
    print(f"[OK] df = {FS_HZ / N_FRAME:.5f} Hz, "
          f"freq range = 0..{N_BIN * FS_HZ / N_FRAME / 1e3:.3f} kHz")

if __name__ == "__main__":
    main()
