// Generated by CIRCT firtool-1.37.0
module DualAdcCapture(
  input  [11:0] io_adc_data_a_raw,
                io_adc_data_b_raw,
  input         io_ora_raw,
                io_orb_raw,
                io_clock,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output [11:0] io_adc_data_a,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output [11:0] io_adc_data_b,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output        io_ora,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output        io_orb
);

  reg [11:0] aReg;
  reg [11:0] bReg;
  reg        oraReg;
  reg        orbReg;
  always @(posedge io_clock) begin
    aReg <= io_adc_data_a_raw;
    bReg <= io_adc_data_b_raw;
    oraReg <= io_ora_raw;
    orbReg <= io_orb_raw;
  end // always @(posedge)
  assign io_adc_data_a = aReg;
  assign io_adc_data_b = bReg;
  assign io_ora = oraReg;
  assign io_orb = orbReg;
endmodule

module DualAdcCaptureTop(
  input         io_clk_40m,
  input  [11:0] io_adc_data_a_raw,
                io_adc_data_b_raw,
  input         io_ora_raw,
                io_orb_raw,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output [11:0] io_adc_data_a,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output [11:0] io_adc_data_b,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output        io_ora,
(* mark_debug = "true", KEEP = "true", DONT_TOUCH = "true" *)
  output        io_orb
);

  DualAdcCapture core (
    .io_adc_data_a_raw (io_adc_data_a_raw),
    .io_adc_data_b_raw (io_adc_data_b_raw),
    .io_ora_raw        (io_ora_raw),
    .io_orb_raw        (io_orb_raw),
    .io_clock          (io_clk_40m),
    .io_adc_data_a     (io_adc_data_a),
    .io_adc_data_b     (io_adc_data_b),
    .io_ora            (io_ora),
    .io_orb            (io_orb)
  );
endmodule