// Generated by CIRCT firtool-1.37.0
module KeyDebounce(
  input        clock,
               reset,
               raw,
  output [3:0] idx
);

  reg         sync0;
  reg         sync1;
  reg  [31:0] counter;
  reg         stable;
  reg         prevStable;
  reg  [3:0]  idxReg;
  wire        _counterNext_T = stable == sync1;
  wire [31:0] _counterNext_T_2 = counter + 32'h1;
  wire        _T = (_counterNext_T ? 32'h0 : _counterNext_T_2) == 32'h3F;
  always @(posedge clock) begin
    if (reset) begin
      sync0 <= 1'h0;
      sync1 <= 1'h0;
      counter <= 32'h0;
      stable <= 1'h0;
      prevStable <= 1'h0;
      idxReg <= 4'h0;
    end
    else begin
      sync0 <= raw;
      sync1 <= sync0;
      if (_T | _counterNext_T)
        counter <= 32'h0;
      else
        counter <= _counterNext_T_2;
      if (_T)
        stable <= sync1;
      prevStable <= stable;
      if (~prevStable & stable) begin
        if (idxReg == 4'h9)
          idxReg <= 4'h0;
        else
          idxReg <= idxReg + 4'h1;
      end
    end
  end // always @(posedge)
  assign idx = idxReg;
endmodule

module KeyDebounce_1(
  input        clock,
               reset,
               raw,
  output [2:0] idx
);

  reg         sync0;
  reg         sync1;
  reg  [31:0] counter;
  reg         stable;
  reg         prevStable;
  reg  [2:0]  idxReg;
  wire        _counterNext_T = stable == sync1;
  wire [31:0] _counterNext_T_2 = counter + 32'h1;
  wire        _T = (_counterNext_T ? 32'h0 : _counterNext_T_2) == 32'h3F;
  always @(posedge clock) begin
    if (reset) begin
      sync0 <= 1'h0;
      sync1 <= 1'h0;
      counter <= 32'h0;
      stable <= 1'h0;
      prevStable <= 1'h0;
      idxReg <= 3'h0;
    end
    else begin
      sync0 <= raw;
      sync1 <= sync0;
      if (_T | _counterNext_T)
        counter <= 32'h0;
      else
        counter <= _counterNext_T_2;
      if (_T)
        stable <= sync1;
      prevStable <= stable;
      if (~prevStable & stable) begin
        if (idxReg == 3'h6)
          idxReg <= 3'h0;
        else
          idxReg <= idxReg + 3'h1;
      end
    end
  end // always @(posedge)
  assign idx = idxReg;
endmodule

module KeyDebounce_2(
  input        clock,
               reset,
               raw,
  output [3:0] idx
);

  reg         sync0;
  reg         sync1;
  reg  [31:0] counter;
  reg         stable;
  reg         prevStable;
  reg  [3:0]  idxReg;
  wire        _counterNext_T = stable == sync1;
  wire [31:0] _counterNext_T_2 = counter + 32'h1;
  wire        _T = (_counterNext_T ? 32'h0 : _counterNext_T_2) == 32'h3F;
  always @(posedge clock) begin
    if (reset) begin
      sync0 <= 1'h0;
      sync1 <= 1'h0;
      counter <= 32'h0;
      stable <= 1'h0;
      prevStable <= 1'h0;
      idxReg <= 4'h0;
    end
    else begin
      sync0 <= raw;
      sync1 <= sync0;
      if (_T | _counterNext_T)
        counter <= 32'h0;
      else
        counter <= _counterNext_T_2;
      if (_T)
        stable <= sync1;
      prevStable <= stable;
      if (~prevStable & stable) begin
        if (idxReg == 4'hA)
          idxReg <= 4'h0;
        else
          idxReg <= idxReg + 4'h1;
      end
    end
  end // always @(posedge)
  assign idx = idxReg;
endmodule

module PhaseAccumulator(
  input         clock,
                reset,
  input  [31:0] inc,
  output [31:0] out
);

  reg [31:0] acc;
  always @(posedge clock) begin
    if (reset)
      acc <= 32'h0;
    else
      acc <= acc + inc;
  end // always @(posedge)
  assign out = acc;
endmodule

module SinLutROM(
  input         clock,
  input  [7:0]  addr,
  output [15:0] out
);

  reg [15:0] casez_tmp;
  initial casez_tmp = 0;
  reg [15:0] out_REG;
  initial out_REG = 0;
  always @(*) begin
    casez (addr)
      8'b00000000:
        casez_tmp = 16'h0;
      8'b00000001:
        casez_tmp = 16'hC9;
      8'b00000010:
        casez_tmp = 16'h192;
      8'b00000011:
        casez_tmp = 16'h25B;
      8'b00000100:
        casez_tmp = 16'h324;
      8'b00000101:
        casez_tmp = 16'h3ED;
      8'b00000110:
        casez_tmp = 16'h4B6;
      8'b00000111:
        casez_tmp = 16'h57F;
      8'b00001000:
        casez_tmp = 16'h648;
      8'b00001001:
        casez_tmp = 16'h711;
      8'b00001010:
        casez_tmp = 16'h7D9;
      8'b00001011:
        casez_tmp = 16'h8A2;
      8'b00001100:
        casez_tmp = 16'h96A;
      8'b00001101:
        casez_tmp = 16'hA33;
      8'b00001110:
        casez_tmp = 16'hAFB;
      8'b00001111:
        casez_tmp = 16'hBC4;
      8'b00010000:
        casez_tmp = 16'hC8C;
      8'b00010001:
        casez_tmp = 16'hD54;
      8'b00010010:
        casez_tmp = 16'hE1C;
      8'b00010011:
        casez_tmp = 16'hEE3;
      8'b00010100:
        casez_tmp = 16'hFAB;
      8'b00010101:
        casez_tmp = 16'h1072;
      8'b00010110:
        casez_tmp = 16'h113A;
      8'b00010111:
        casez_tmp = 16'h1201;
      8'b00011000:
        casez_tmp = 16'h12C8;
      8'b00011001:
        casez_tmp = 16'h138F;
      8'b00011010:
        casez_tmp = 16'h1455;
      8'b00011011:
        casez_tmp = 16'h151C;
      8'b00011100:
        casez_tmp = 16'h15E2;
      8'b00011101:
        casez_tmp = 16'h16A8;
      8'b00011110:
        casez_tmp = 16'h176E;
      8'b00011111:
        casez_tmp = 16'h1833;
      8'b00100000:
        casez_tmp = 16'h18F9;
      8'b00100001:
        casez_tmp = 16'h19BE;
      8'b00100010:
        casez_tmp = 16'h1A82;
      8'b00100011:
        casez_tmp = 16'h1B47;
      8'b00100100:
        casez_tmp = 16'h1C0B;
      8'b00100101:
        casez_tmp = 16'h1CCF;
      8'b00100110:
        casez_tmp = 16'h1D93;
      8'b00100111:
        casez_tmp = 16'h1E57;
      8'b00101000:
        casez_tmp = 16'h1F1A;
      8'b00101001:
        casez_tmp = 16'h1FDD;
      8'b00101010:
        casez_tmp = 16'h209F;
      8'b00101011:
        casez_tmp = 16'h2161;
      8'b00101100:
        casez_tmp = 16'h2223;
      8'b00101101:
        casez_tmp = 16'h22E5;
      8'b00101110:
        casez_tmp = 16'h23A6;
      8'b00101111:
        casez_tmp = 16'h2467;
      8'b00110000:
        casez_tmp = 16'h2528;
      8'b00110001:
        casez_tmp = 16'h25E8;
      8'b00110010:
        casez_tmp = 16'h26A8;
      8'b00110011:
        casez_tmp = 16'h2767;
      8'b00110100:
        casez_tmp = 16'h2826;
      8'b00110101:
        casez_tmp = 16'h28E5;
      8'b00110110:
        casez_tmp = 16'h29A3;
      8'b00110111:
        casez_tmp = 16'h2A61;
      8'b00111000:
        casez_tmp = 16'h2B1F;
      8'b00111001:
        casez_tmp = 16'h2BDC;
      8'b00111010:
        casez_tmp = 16'h2C99;
      8'b00111011:
        casez_tmp = 16'h2D55;
      8'b00111100:
        casez_tmp = 16'h2E11;
      8'b00111101:
        casez_tmp = 16'h2ECC;
      8'b00111110:
        casez_tmp = 16'h2F87;
      8'b00111111:
        casez_tmp = 16'h3041;
      8'b01000000:
        casez_tmp = 16'h30FB;
      8'b01000001:
        casez_tmp = 16'h31B5;
      8'b01000010:
        casez_tmp = 16'h326E;
      8'b01000011:
        casez_tmp = 16'h3326;
      8'b01000100:
        casez_tmp = 16'h33DF;
      8'b01000101:
        casez_tmp = 16'h3496;
      8'b01000110:
        casez_tmp = 16'h354D;
      8'b01000111:
        casez_tmp = 16'h3604;
      8'b01001000:
        casez_tmp = 16'h36BA;
      8'b01001001:
        casez_tmp = 16'h376F;
      8'b01001010:
        casez_tmp = 16'h3824;
      8'b01001011:
        casez_tmp = 16'h38D9;
      8'b01001100:
        casez_tmp = 16'h398C;
      8'b01001101:
        casez_tmp = 16'h3A40;
      8'b01001110:
        casez_tmp = 16'h3AF2;
      8'b01001111:
        casez_tmp = 16'h3BA5;
      8'b01010000:
        casez_tmp = 16'h3C56;
      8'b01010001:
        casez_tmp = 16'h3D07;
      8'b01010010:
        casez_tmp = 16'h3DB8;
      8'b01010011:
        casez_tmp = 16'h3E68;
      8'b01010100:
        casez_tmp = 16'h3F17;
      8'b01010101:
        casez_tmp = 16'h3FC5;
      8'b01010110:
        casez_tmp = 16'h4073;
      8'b01010111:
        casez_tmp = 16'h4121;
      8'b01011000:
        casez_tmp = 16'h41CE;
      8'b01011001:
        casez_tmp = 16'h427A;
      8'b01011010:
        casez_tmp = 16'h4325;
      8'b01011011:
        casez_tmp = 16'h43D0;
      8'b01011100:
        casez_tmp = 16'h447A;
      8'b01011101:
        casez_tmp = 16'h4524;
      8'b01011110:
        casez_tmp = 16'h45CD;
      8'b01011111:
        casez_tmp = 16'h4675;
      8'b01100000:
        casez_tmp = 16'h471C;
      8'b01100001:
        casez_tmp = 16'h47C3;
      8'b01100010:
        casez_tmp = 16'h4869;
      8'b01100011:
        casez_tmp = 16'h490F;
      8'b01100100:
        casez_tmp = 16'h49B4;
      8'b01100101:
        casez_tmp = 16'h4A58;
      8'b01100110:
        casez_tmp = 16'h4AFB;
      8'b01100111:
        casez_tmp = 16'h4B9D;
      8'b01101000:
        casez_tmp = 16'h4C3F;
      8'b01101001:
        casez_tmp = 16'h4CE0;
      8'b01101010:
        casez_tmp = 16'h4D81;
      8'b01101011:
        casez_tmp = 16'h4E20;
      8'b01101100:
        casez_tmp = 16'h4EBF;
      8'b01101101:
        casez_tmp = 16'h4F5D;
      8'b01101110:
        casez_tmp = 16'h4FFB;
      8'b01101111:
        casez_tmp = 16'h5097;
      8'b01110000:
        casez_tmp = 16'h5133;
      8'b01110001:
        casez_tmp = 16'h51CE;
      8'b01110010:
        casez_tmp = 16'h5268;
      8'b01110011:
        casez_tmp = 16'h5302;
      8'b01110100:
        casez_tmp = 16'h539B;
      8'b01110101:
        casez_tmp = 16'h5432;
      8'b01110110:
        casez_tmp = 16'h54C9;
      8'b01110111:
        casez_tmp = 16'h5560;
      8'b01111000:
        casez_tmp = 16'h55F5;
      8'b01111001:
        casez_tmp = 16'h568A;
      8'b01111010:
        casez_tmp = 16'h571D;
      8'b01111011:
        casez_tmp = 16'h57B0;
      8'b01111100:
        casez_tmp = 16'h5842;
      8'b01111101:
        casez_tmp = 16'h58D3;
      8'b01111110:
        casez_tmp = 16'h5964;
      8'b01111111:
        casez_tmp = 16'h59F3;
      8'b10000000:
        casez_tmp = 16'h5A82;
      8'b10000001:
        casez_tmp = 16'h5B0F;
      8'b10000010:
        casez_tmp = 16'h5B9C;
      8'b10000011:
        casez_tmp = 16'h5C28;
      8'b10000100:
        casez_tmp = 16'h5CB3;
      8'b10000101:
        casez_tmp = 16'h5D3E;
      8'b10000110:
        casez_tmp = 16'h5DC7;
      8'b10000111:
        casez_tmp = 16'h5E4F;
      8'b10001000:
        casez_tmp = 16'h5ED7;
      8'b10001001:
        casez_tmp = 16'h5F5D;
      8'b10001010:
        casez_tmp = 16'h5FE3;
      8'b10001011:
        casez_tmp = 16'h6068;
      8'b10001100:
        casez_tmp = 16'h60EB;
      8'b10001101:
        casez_tmp = 16'h616E;
      8'b10001110:
        casez_tmp = 16'h61F0;
      8'b10001111:
        casez_tmp = 16'h6271;
      8'b10010000:
        casez_tmp = 16'h62F1;
      8'b10010001:
        casez_tmp = 16'h6370;
      8'b10010010:
        casez_tmp = 16'h63EE;
      8'b10010011:
        casez_tmp = 16'h646C;
      8'b10010100:
        casez_tmp = 16'h64E8;
      8'b10010101:
        casez_tmp = 16'h6563;
      8'b10010110:
        casez_tmp = 16'h65DD;
      8'b10010111:
        casez_tmp = 16'h6656;
      8'b10011000:
        casez_tmp = 16'h66CF;
      8'b10011001:
        casez_tmp = 16'h6746;
      8'b10011010:
        casez_tmp = 16'h67BC;
      8'b10011011:
        casez_tmp = 16'h6832;
      8'b10011100:
        casez_tmp = 16'h68A6;
      8'b10011101:
        casez_tmp = 16'h6919;
      8'b10011110:
        casez_tmp = 16'h698B;
      8'b10011111:
        casez_tmp = 16'h69FD;
      8'b10100000:
        casez_tmp = 16'h6A6D;
      8'b10100001:
        casez_tmp = 16'h6ADC;
      8'b10100010:
        casez_tmp = 16'h6B4A;
      8'b10100011:
        casez_tmp = 16'h6BB7;
      8'b10100100:
        casez_tmp = 16'h6C23;
      8'b10100101:
        casez_tmp = 16'h6C8E;
      8'b10100110:
        casez_tmp = 16'h6CF8;
      8'b10100111:
        casez_tmp = 16'h6D61;
      8'b10101000:
        casez_tmp = 16'h6DC9;
      8'b10101001:
        casez_tmp = 16'h6E30;
      8'b10101010:
        casez_tmp = 16'h6E96;
      8'b10101011:
        casez_tmp = 16'h6EFB;
      8'b10101100:
        casez_tmp = 16'h6F5E;
      8'b10101101:
        casez_tmp = 16'h6FC1;
      8'b10101110:
        casez_tmp = 16'h7022;
      8'b10101111:
        casez_tmp = 16'h7083;
      8'b10110000:
        casez_tmp = 16'h70E2;
      8'b10110001:
        casez_tmp = 16'h7140;
      8'b10110010:
        casez_tmp = 16'h719D;
      8'b10110011:
        casez_tmp = 16'h71F9;
      8'b10110100:
        casez_tmp = 16'h7254;
      8'b10110101:
        casez_tmp = 16'h72AE;
      8'b10110110:
        casez_tmp = 16'h7307;
      8'b10110111:
        casez_tmp = 16'h735E;
      8'b10111000:
        casez_tmp = 16'h73B5;
      8'b10111001:
        casez_tmp = 16'h740A;
      8'b10111010:
        casez_tmp = 16'h745F;
      8'b10111011:
        casez_tmp = 16'h74B2;
      8'b10111100:
        casez_tmp = 16'h7504;
      8'b10111101:
        casez_tmp = 16'h7555;
      8'b10111110:
        casez_tmp = 16'h75A5;
      8'b10111111:
        casez_tmp = 16'h75F3;
      8'b11000000:
        casez_tmp = 16'h7641;
      8'b11000001:
        casez_tmp = 16'h768D;
      8'b11000010:
        casez_tmp = 16'h76D8;
      8'b11000011:
        casez_tmp = 16'h7722;
      8'b11000100:
        casez_tmp = 16'h776B;
      8'b11000101:
        casez_tmp = 16'h77B3;
      8'b11000110:
        casez_tmp = 16'h77FA;
      8'b11000111:
        casez_tmp = 16'h783F;
      8'b11001000:
        casez_tmp = 16'h7884;
      8'b11001001:
        casez_tmp = 16'h78C7;
      8'b11001010:
        casez_tmp = 16'h7909;
      8'b11001011:
        casez_tmp = 16'h794A;
      8'b11001100:
        casez_tmp = 16'h7989;
      8'b11001101:
        casez_tmp = 16'h79C8;
      8'b11001110:
        casez_tmp = 16'h7A05;
      8'b11001111:
        casez_tmp = 16'h7A41;
      8'b11010000:
        casez_tmp = 16'h7A7C;
      8'b11010001:
        casez_tmp = 16'h7AB6;
      8'b11010010:
        casez_tmp = 16'h7AEE;
      8'b11010011:
        casez_tmp = 16'h7B26;
      8'b11010100:
        casez_tmp = 16'h7B5C;
      8'b11010101:
        casez_tmp = 16'h7B91;
      8'b11010110:
        casez_tmp = 16'h7BC5;
      8'b11010111:
        casez_tmp = 16'h7BF8;
      8'b11011000:
        casez_tmp = 16'h7C29;
      8'b11011001:
        casez_tmp = 16'h7C59;
      8'b11011010:
        casez_tmp = 16'h7C88;
      8'b11011011:
        casez_tmp = 16'h7CB6;
      8'b11011100:
        casez_tmp = 16'h7CE3;
      8'b11011101:
        casez_tmp = 16'h7D0E;
      8'b11011110:
        casez_tmp = 16'h7D39;
      8'b11011111:
        casez_tmp = 16'h7D62;
      8'b11100000:
        casez_tmp = 16'h7D89;
      8'b11100001:
        casez_tmp = 16'h7DB0;
      8'b11100010:
        casez_tmp = 16'h7DD5;
      8'b11100011:
        casez_tmp = 16'h7DFA;
      8'b11100100:
        casez_tmp = 16'h7E1D;
      8'b11100101:
        casez_tmp = 16'h7E3E;
      8'b11100110:
        casez_tmp = 16'h7E5F;
      8'b11100111:
        casez_tmp = 16'h7E7E;
      8'b11101000:
        casez_tmp = 16'h7E9C;
      8'b11101001:
        casez_tmp = 16'h7EB9;
      8'b11101010:
        casez_tmp = 16'h7ED5;
      8'b11101011:
        casez_tmp = 16'h7EEF;
      8'b11101100:
        casez_tmp = 16'h7F09;
      8'b11101101:
        casez_tmp = 16'h7F21;
      8'b11101110:
        casez_tmp = 16'h7F37;
      8'b11101111:
        casez_tmp = 16'h7F4D;
      8'b11110000:
        casez_tmp = 16'h7F61;
      8'b11110001:
        casez_tmp = 16'h7F74;
      8'b11110010:
        casez_tmp = 16'h7F86;
      8'b11110011:
        casez_tmp = 16'h7F97;
      8'b11110100:
        casez_tmp = 16'h7FA6;
      8'b11110101:
        casez_tmp = 16'h7FB4;
      8'b11110110:
        casez_tmp = 16'h7FC1;
      8'b11110111:
        casez_tmp = 16'h7FCD;
      8'b11111000:
        casez_tmp = 16'h7FD8;
      8'b11111001:
        casez_tmp = 16'h7FE1;
      8'b11111010:
        casez_tmp = 16'h7FE9;
      8'b11111011:
        casez_tmp = 16'h7FF0;
      8'b11111100:
        casez_tmp = 16'h7FF5;
      8'b11111101:
        casez_tmp = 16'h7FF9;
      8'b11111110:
        casez_tmp = 16'h7FFD;
      default:
        casez_tmp = 16'h7FFE;
    endcase
  end // always @(*)
  always @(posedge clock)
    out_REG <= casez_tmp;
  assign out = out_REG;
endmodule

module SinGen(
  input         clock,
  input  [9:0]  phase,
  output [15:0] out
);

  wire [15:0] _lut_out;
  SinLutROM lut (
    .clock (clock),
    .addr  ({8{phase[8]}} ^ phase[7:0]),
    .out   (_lut_out)
  );
  assign out = phase[9] ? 16'h0 - _lut_out : _lut_out;
endmodule

module AmModulator(
  input         clock,
                reset,
  input  [9:0]  io_mod_phase,
                io_carrier_phase,
  input  [15:0] io_k_am,
  input  [13:0] io_k_amp,
  output [13:0] io_out_code
);

  wire [15:0] _cGen_out;
  wire [15:0] _mGen_out;
  reg  [15:0] cSignR;
  initial cSignR = 0;
  reg  [15:0] mSignR;
  initial mSignR = 0;
  reg  [33:0] envQ30uR;
  initial envQ30uR = 0;
  reg  [49:0] amRawQ30R;
  initial amRawQ30R = 0;
  reg  [49:0] amRawQ30R2;
  initial amRawQ30R2 = 0;
  reg  [35:0] mulInvR;
  initial mulInvR = 0;
  reg  [34:0] ampProdR;
  initial ampProdR = 0;
  reg  [34:0] ampProdR2;
  initial ampProdR2 = 0;
  wire [14:0] _minV_T_1 = 15'h0 - {1'h0, io_k_amp};
  wire [15:0] _offset_T_1 =
    ($signed(ampProdR2[34:15]) > $signed({6'h0, io_k_amp})
       ? {2'h0, io_k_amp}
       : $signed(ampProdR2[34:15]) < $signed({{5{_minV_T_1[14]}}, _minV_T_1})
           ? {_minV_T_1[14], _minV_T_1}
           : ampProdR2[30:15]) + 16'h2000;
  always @(posedge clock) begin
    if (reset) begin
      cSignR <= 16'h0;
      mSignR <= 16'h0;
      envQ30uR <= 34'h0;
      amRawQ30R <= 50'h0;
      amRawQ30R2 <= 50'h0;
      mulInvR <= 36'h0;
      ampProdR <= 35'h0;
      ampProdR2 <= 35'h0;
    end
    else begin
      cSignR <= _cGen_out;
      mSignR <= _mGen_out;
      envQ30uR <=
        {2'h0, {{16{io_k_am[15]}}, io_k_am} * {{16{mSignR[15]}}, mSignR}} + 34'h40000000;
      amRawQ30R <= {{16{envQ30uR[33]}}, envQ30uR} * {{34{cSignR[15]}}, cSignR};
      amRawQ30R2 <= amRawQ30R;
      mulInvR <= {{16{amRawQ30R2[49]}}, amRawQ30R2[49:30]} * 36'h435E;
      ampProdR <= {{14{mulInvR[35]}}, mulInvR[35:15]} * {{21{io_k_amp[13]}}, io_k_amp};
      ampProdR2 <= ampProdR;
    end
  end // always @(posedge)
  SinGen mGen (
    .clock (clock),
    .phase (io_mod_phase),
    .out   (_mGen_out)
  );
  SinGen cGen (
    .clock (clock),
    .phase (io_carrier_phase),
    .out   (_cGen_out)
  );
  assign io_out_code =
    $signed(_offset_T_1) < 16'sh0
      ? 14'h0
      : $signed(_offset_T_1) > 16'sh3FFF ? 14'h3FFF : _offset_T_1[13:0];
endmodule

module FmModulator(
  input         clock,
                reset,
  input  [9:0]  io_mod_phase,
  input  [31:0] io_k_dev,
  input  [13:0] io_k_amp,
  output [13:0] io_out_code
);

  wire [15:0] _cGen_out;
  wire [31:0] _accum_out;
  wire [15:0] _mGen_out;
  reg  [15:0] mSignR;
  initial mSignR = 0;
  reg  [47:0] mulDevR;
  initial mulDevR = 0;
  reg  [14:0] ampScaledR;
  initial ampScaledR = 0;
  reg  [14:0] ampScaledR2;
  initial ampScaledR2 = 0;
  wire [14:0] _T_2 = 15'h0 - {1'h0, io_k_amp};
  wire [15:0] _offset_T_1 =
    ($signed(ampScaledR2) > $signed({1'h0, io_k_amp})
       ? {2'h0, io_k_amp}
       : $signed(ampScaledR2) < $signed(_T_2)
           ? {_T_2[14], _T_2}
           : {ampScaledR2[14], ampScaledR2}) + 16'h2000;
  wire [29:0] _ampScaled_T =
    {{14{_cGen_out[15]}}, _cGen_out} * {{16{io_k_amp[13]}}, io_k_amp};
  always @(posedge clock) begin
    if (reset) begin
      mSignR <= 16'h0;
      mulDevR <= 48'h0;
      ampScaledR <= 15'h0;
      ampScaledR2 <= 15'h0;
    end
    else begin
      mSignR <= _mGen_out;
      mulDevR <= {{16{io_k_dev[31]}}, io_k_dev} * {{32{mSignR[15]}}, mSignR};
      ampScaledR <= _ampScaled_T[29:15];
      ampScaledR2 <= ampScaledR;
    end
  end // always @(posedge)
  SinGen mGen (
    .clock (clock),
    .phase (io_mod_phase),
    .out   (_mGen_out)
  );
  wire [31:0] _accum_inc = 33'h1EB851EC + {{1{mulDevR[47]}}, mulDevR[46:15]};
  PhaseAccumulator accum (
    .clock (clock),
    .reset (reset),
    .inc (_accum_inc),
    .out   (_accum_out)
  );
  SinGen cGen (
    .clock (clock),
    .phase (_accum_out[31:22]),
    .out   (_cGen_out)
  );
  assign io_out_code =
    $signed(_offset_T_1) < 16'sh0
      ? 14'h0
      : $signed(_offset_T_1) > 16'sh3FFF ? 14'h3FFF : _offset_T_1[13:0];
endmodule

module AD9764Top(
  input         clock,
                reset,
                io_key1,
                io_key2,
                io_key3,
  output [13:0] io_cha_data,
                io_chb_data,
  output [3:0]  io_status_led
);

  wire [13:0] _fmMod_io_out_code;
  wire [13:0] _amMod_io_out_code;
  wire [31:0] _modPacc_out;
  wire [31:0] _carPacc_out;
  wire [3:0]  _key3Db_idx;
  wire [2:0]  _key2Db_idx;
  wire [3:0]  _key1Db_idx;
  reg         key1Sync0;
  reg         key1Sync1;
  reg         key1Sync2;
  reg         key2Sync0;
  reg         key2Sync1;
  reg         key2Sync2;
  reg         key3Sync0;
  reg         key3Sync1;
  reg         key3Sync2;
  reg  [13:0] kAmp;
  initial kAmp = 0;
  reg  [15:0] kAm;
  initial kAm = 0;
  reg  [31:0] kDev;
  initial kDev = 0;
  reg  [13:0] chaReg;
  initial chaReg = 0;
  reg  [13:0] chbReg;
  initial chbReg = 0;
  always @(posedge clock) begin
    if (reset) begin
      key1Sync0 <= 1'h0;
      key1Sync1 <= 1'h0;
      key1Sync2 <= 1'h0;
      key2Sync0 <= 1'h0;
      key2Sync1 <= 1'h0;
      key2Sync2 <= 1'h0;
      key3Sync0 <= 1'h0;
      key3Sync1 <= 1'h0;
      key3Sync2 <= 1'h0;
      kAmp <= 14'h0;
      kAm <= 16'h0;
      kDev <= 32'h0;
      chaReg <= 14'h0;
      chbReg <= 14'h0;
    end
    else begin
      key1Sync0 <= io_key1;
      key1Sync1 <= key1Sync0;
      key1Sync2 <= key1Sync1;
      key2Sync0 <= io_key2;
      key2Sync1 <= key2Sync0;
      key2Sync2 <= key2Sync1;
      key3Sync0 <= io_key3;
      key3Sync1 <= key3Sync0;
      key3Sync2 <= key3Sync1;
      kAmp <=
        (_key1Db_idx == 4'h0 ? 14'h111 : 14'h0) | (_key1Db_idx == 4'h1 ? 14'h222 : 14'h0)
        | (_key1Db_idx == 4'h2 ? 14'h333 : 14'h0)
        | (_key1Db_idx == 4'h3 ? 14'h444 : 14'h0)
        | (_key1Db_idx == 4'h4 ? 14'h555 : 14'h0)
        | (_key1Db_idx == 4'h5 ? 14'h666 : 14'h0)
        | (_key1Db_idx == 4'h6 ? 14'h777 : 14'h0)
        | (_key1Db_idx == 4'h7 ? 14'h888 : 14'h0)
        | (_key1Db_idx == 4'h8 ? 14'h999 : 14'h0)
        | (_key1Db_idx == 4'h9 ? 14'hAAA : 14'h0);
      kAm <=
        (_key2Db_idx == 3'h0 ? 16'h2666 : 16'h0)
        | (_key2Db_idx == 3'h1 ? 16'h3333 : 16'h0) | {1'h0, _key2Db_idx == 3'h2, 14'h0}
        | (_key2Db_idx == 3'h3 ? 16'h4CCC : 16'h0)
        | (_key2Db_idx == 3'h4 ? 16'h5999 : 16'h0)
        | (_key2Db_idx == 3'h5 ? 16'h6666 : 16'h0)
        | (_key2Db_idx == 3'h6 ? 16'h7332 : 16'h0);
      kDev <=
        (_key3Db_idx == 4'h0 ? 32'h192A7 : 32'h0)
        | (_key3Db_idx == 4'h1 ? 32'h1AD7F : 32'h0)
        | (_key3Db_idx == 4'h2 ? 32'h1C857 : 32'h0)
        | (_key3Db_idx == 4'h3 ? 32'h1E32F : 32'h0)
        | (_key3Db_idx == 4'h4 ? 32'h1FE07 : 32'h0)
        | (_key3Db_idx == 4'h5 ? 32'h218DF : 32'h0)
        | (_key3Db_idx == 4'h6 ? 32'h233B7 : 32'h0)
        | (_key3Db_idx == 4'h7 ? 32'h24E8F : 32'h0)
        | (_key3Db_idx == 4'h8 ? 32'h26967 : 32'h0)
        | (_key3Db_idx == 4'h9 ? 32'h2843F : 32'h0)
        | (_key3Db_idx == 4'hA ? 32'h29F17 : 32'h0);
      chaReg <= _amMod_io_out_code;
      chbReg <= _fmMod_io_out_code;
    end
  end // always @(posedge)
  KeyDebounce key1Db (
    .clock (clock),
    .reset (reset),
    .raw   (key1Sync2),
    .idx   (_key1Db_idx)
  );
  KeyDebounce_1 key2Db (
    .clock (clock),
    .reset (reset),
    .raw   (key2Sync2),
    .idx   (_key2Db_idx)
  );
  KeyDebounce_2 key3Db (
    .clock (clock),
    .reset (reset),
    .raw   (key3Sync2),
    .idx   (_key3Db_idx)
  );
  PhaseAccumulator carPacc (
    .clock (clock),
    .reset (reset),
    .inc   (32'h1EB851EC),
    .out   (_carPacc_out)
  );
  PhaseAccumulator modPacc (
    .clock (clock),
    .reset (reset),
    .inc   (32'h53E2D),
    .out   (_modPacc_out)
  );
  AmModulator amMod (
    .clock            (clock),
    .reset            (reset),
    .io_mod_phase     (_modPacc_out[31:22]),
    .io_carrier_phase (_carPacc_out[31:22]),
    .io_k_am          (kAm),
    .io_k_amp         (kAmp),
    .io_out_code      (_amMod_io_out_code)
  );
  FmModulator fmMod (
    .clock        (clock),
    .reset        (reset),
    .io_mod_phase (_modPacc_out[31:22]),
    .io_k_dev     (kDev),
    .io_k_amp     (kAmp),
    .io_out_code  (_fmMod_io_out_code)
  );
  assign io_cha_data = chaReg;
  assign io_chb_data = chbReg;
  assign io_status_led = {~reset, _key3Db_idx[0], _key2Db_idx[0], _key1Db_idx[0]};
endmodule

