# top.xdc - AD9764 DAC_exercise pin / timing constraints
create_clock -period 20.000 -name clk_50m -waveform {0.000 10.000} [get_ports clk_50m]
set_property PACKAGE_PIN U18 [get_ports clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]

set_property PACKAGE_PIN L16 [get_ports {cha_data[0]}]
set_property PACKAGE_PIN H20 [get_ports {cha_data[1]}]
set_property PACKAGE_PIN J20 [get_ports {cha_data[2]}]
set_property PACKAGE_PIN J19 [get_ports {cha_data[3]}]
set_property PACKAGE_PIN K19 [get_ports {cha_data[4]}]
set_property PACKAGE_PIN K18 [get_ports {cha_data[5]}]
set_property PACKAGE_PIN K17 [get_ports {cha_data[6]}]
set_property PACKAGE_PIN M20 [get_ports {cha_data[7]}]
set_property PACKAGE_PIN M19 [get_ports {cha_data[8]}]
set_property PACKAGE_PIN L20 [get_ports {cha_data[9]}]
set_property PACKAGE_PIN L19 [get_ports {cha_data[10]}]
set_property PACKAGE_PIN H18 [get_ports {cha_data[11]}]
set_property PACKAGE_PIN J18 [get_ports {cha_data[12]}]
set_property PACKAGE_PIN G20 [get_ports {cha_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cha_data[*]}]
set_property SLEW SLOW [get_ports {cha_data[*]}]
set_property DRIVE 4 [get_ports {cha_data[*]}]

set_property PACKAGE_PIN G19 [get_ports cha_clk]
set_property IOSTANDARD LVCMOS33 [get_ports cha_clk]
set_property SLEW SLOW [get_ports cha_clk]
set_property DRIVE 4 [get_ports cha_clk]

set_property PACKAGE_PIN J14 [get_ports {chb_data[0]}]
set_property PACKAGE_PIN K14 [get_ports {chb_data[1]}]
set_property PACKAGE_PIN G15 [get_ports {chb_data[2]}]
set_property PACKAGE_PIN H15 [get_ports {chb_data[3]}]
set_property PACKAGE_PIN H17 [get_ports {chb_data[4]}]
set_property PACKAGE_PIN H16 [get_ports {chb_data[5]}]
set_property PACKAGE_PIN G18 [get_ports {chb_data[6]}]
set_property PACKAGE_PIN G17 [get_ports {chb_data[7]}]
set_property PACKAGE_PIN E19 [get_ports {chb_data[8]}]
set_property PACKAGE_PIN E18 [get_ports {chb_data[9]}]
set_property PACKAGE_PIN D20 [get_ports {chb_data[10]}]
set_property PACKAGE_PIN D19 [get_ports {chb_data[11]}]
set_property PACKAGE_PIN M18 [get_ports {chb_data[12]}]
set_property PACKAGE_PIN M17 [get_ports {chb_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chb_data[*]}]
set_property SLEW SLOW [get_ports {chb_data[*]}]
set_property DRIVE 4 [get_ports {chb_data[*]}]

set_property PACKAGE_PIN L17 [get_ports chb_clk]
set_property IOSTANDARD LVCMOS33 [get_ports chb_clk]
set_property SLEW SLOW [get_ports chb_clk]
set_property DRIVE 4 [get_ports chb_clk]

set_property PACKAGE_PIN M14 [get_ports {status_led[0]}]
set_property PACKAGE_PIN M15 [get_ports {status_led[1]}]
set_property PACKAGE_PIN K16 [get_ports {status_led[2]}]
set_property PACKAGE_PIN J16 [get_ports {status_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {status_led[*]}]
set_false_path -to [get_ports {status_led[*]}]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]